/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class testjni_Compter */

#ifndef _Included_testjni_Compter
#define _Included_testjni_Compter
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     testjni_Compter
 * Method:    n_Compter
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_testjni_Compter_n_1Compter(JNIEnv *, jobject);

/*
 * Class:     testjni_Compter
 * Method:    n_getValue
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_testjni_Compter_n_1getValue(JNIEnv *, jobject);

/*
 * Class:     testjni_Compter
 * Method:    n_increment
 * Signature: (D)V
 */
JNIEXPORT void JNICALL Java_testjni_Compter_n_1increment(JNIEnv *, jobject,
                                                         jdouble);

#ifdef __cplusplus
}
#endif
#endif
